{{- if and .Values.backup.enabled .Values.backup.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "airgap-postgres.fullname" . }}-backup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airgap-postgres.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
spec:
  accessModes:
    {{- toYaml .Values.backup.persistence.accessModes | nindent 4 }}
  {{- if .Values.backup.persistence.storageClass }}
  storageClassName: {{ .Values.backup.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backup.persistence.size | quote }}
{{- end }}
