{{- if .Values.haproxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airgap-postgres.fullname" . }}-haproxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airgap-postgres.labels" . | nindent 4 }}
    app.kubernetes.io/component: haproxy
spec:
  type: {{ .Values.haproxy.service.type }}
  ports:
    - name: postgresql
      port: {{ .Values.haproxy.service.port }}
      targetPort: postgresql
      protocol: TCP
    - name: postgresql-readonly
      port: {{ .Values.haproxy.service.readOnlyPort }}
      targetPort: postgresql-ro
      protocol: TCP
    - name: stats
      port: 8404
      targetPort: stats
      protocol: TCP
  selector:
    {{- include "airgap-postgres.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: haproxy
{{- end }}
