apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airgap-postgres.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airgap-postgres.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.password | default (randAlphaNum 16) | b64enc | quote }}
  postgresql-postgres-password: {{ .Values.postgresql.postgresPassword | default (randAlphaNum 16) | b64enc | quote }}
  {{- if .Values.postgresql.replication.enabled }}
  postgresql-replication-password: {{ .Values.postgresql.replication.password | default (randAlphaNum 16) | b64enc | quote }}
  {{- end }}
